### ISSUE TITLE
Incorrect license for stackmat.js

### ISSUE THREAD

**Issue by xsrvmy** [DallasMcNeil/Block-Keeper#4]
stackmat.js is under the MIT License, but the license.txt file in the project states that it is under the GPL license. This probably would confuse others and you shoudl correct it.

**Comment by DallasMcNeil** [comment]
Block Keeper uses this Stackmat library (https://github.com/cs0x7f/stackmat) which is under the GPL licence. Not to be confused with (https://github.com/timhabermaas/stackmat.js) which does use MIT. The names are very similar but they are seperate libraries.

**Comment by xsrvmy** [comment]
That was my mistake. Just wondering, doesn't this project have to be under GPL then?

**Comment by DallasMcNeil** [comment]
Re-reading the GPL Licence, yes, as the Stackmat library is redistributed, Block Keeper must also be under the same license. I will correct this issue in the next version. Thank you for pointing this out.

**Comment by xsrvmy** [comment]
I actually believe there is another solution if you want most of the code for the timer to be under MIT. You can release a version without stackmat functionality under MIT and one with stackmat under GPL. I have definitely seen big projects do this.

**Comment by xsrvmy** [comment]
Never mind. Some of the scrmablers, noticeably the 3x3 scrambler, are GPL too.

**Comment by DallasMcNeil** [comment]
Although I prefer MIT, I guess it will need to be under GPL due to these libraries.

**Comment by xsrvmy** [comment]
So I just searched about alternatives to the scramblers as well as the stackmat. I found a MIT licensed random state scrambler for 3x3 online, and there is stackmat.js for the stackmat timer. Most of the other scrambler are pretty easy to program, as they are either random moves or can be easily solved with an exhaustive search. The only one that can cause an issue is the sq1 scrambler.
Also, given that you used the cstimer stackmat library, was this timer based off cstimer by any chance?

**Comment by DallasMcNeil** [comment]
An advantage of the current scramblers is that most of them also generate an image which is a very popular feature, so any replacement would also need to do that. I tried Stackmat.js before csTimer's Stackmat library but I couldn't get it to work when I tested it, where I could get csTimer to work with my Stackmat with no problems. csTimer has been an inspiration because it is a very fully featured and popular timer, but I found there were things (like session and scramble management) that could be improved or treated differently. I also wanted a desktop timer that could take advantage of things like a camera that also had a clean interface and ran natively. So a general dissatisfaction for a strong standalone desktop timer really prompted me to make Block Keeper to fill that gap but csTimer did influence part of it's design.

**Comment by xsrvmy** [comment]
I actually made a java program that can parse algs for cubic puzzles and apply moves to it. I can easily rewrite that in js. Drawing an image from the resulting state is really easy.
Really, the scramble image program is just time consuming to make, but it's not that hard to program.

**Comment by DallasMcNeil** [comment]
That's really cool. It would be awesome but only if it could be done for all puzzles (including non-cubic puzzles like skewb, megaminx, square-1 and clock). Which seems like a lot of effort considering the minor benefit.
